{{- if .Values.secrets.enabled -}}
{{- $files := .Files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virtual-pet.fullname" . }}
  labels:
    {{- include "virtual-pet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $path := .Values.secrets.values }}
  {{ $key }}: {{ $files.Get $path | b64enc }}
  {{- end }}
{{- end }}